
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/regression_jul3_strands_augmented/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
