
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/regression_jul7_jittered/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
