
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/celltype_k562_jul25/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
