
    {
        "class": "hdf5_data_loader.MultimodalAtOnceDataLoader",
        "kwargs": {
           "path_to_hdf5": "../hdf5files/celltype_k562_jul25/valid_data.hdf5",
           "strip_enclosing_dictionary": True
        }
    }
    
