
    {
        "class": "hdf5_data_loader.MultimodalAtOnceDataLoader",
        "kwargs": {
           "path_to_hdf5": "../hdf5files/regression_jul12_normalized/valid_data.hdf5",
           "strip_enclosing_dictionary": True
        }
    }
    
