[
{
        "other_data_loaders":{
            "train": {
                "class": "hdf5_data_loader.MultimodalBatchDataLoader",
                "kwargs": {
                    "batch_size": 500,
                    "path_to_hdf5": "../hdf5files/regressionJun24Positives/train_data.hdf5",
                    "num_to_load_for_eval": 51838,
                    "bundle_x_and_y_in_generator": False,
                    "strip_enclosing_dictionary": True
                }
            }
        },
    "model_creator":{
        "class": "flexible_keras.FlexibleKerasSequential",
        "kwargs": {
           "layers_config": [
            {
                "name": "conv1",
                "class": "keras.layers.convolutional.Convolution1D",
                "kwargs": {
                    "input_shape": [
                        2000,
                        4
                    ],
                    "nb_filter": 20,
                    "filter_length": 19
                }
            },
            {
                "name": "conv1_batchnorm",
                "class": "keras.layers.normalization.BatchNormalization",
                "kwargs": {
                    "axis": -1
                }
            },
            {
                "name": "conv1_act",
                "class": "keras.layers.core.Activation",
                "kwargs": {
                    "activation": "relu"
                }
            },
            {
                "name": "global_avg_pooling",
                "class": "keras.layers.pooling.GlobalAveragePooling1D",
                "kwargs": {
                #    "pool_length": 3,
                #    "stride": 3
                }
            },
            #{
            #    "name": "flatten",
            #    "class": "keras.layers.core.Flatten",
            #    "kwargs": {}
            #},
            {
                "name": "fc1",
                "class": "keras.layers.core.Dense",
                "kwargs": {
                    "output_dim": 100,
                    "activity_regularizer": {
                        "autoload": true,
                        "class": "keras.regularizers.ActivityRegularizer",
                        "kwargs": {
                            "l1": 1e-05
                        }
                    },
                    #"W_constraint": {
                    #    "autoload": true,
                    #    "class": "keras.constraints.maxnorm",
                    #    "kwargs": {
                    #        "m": 7,
                    #        "axis": 0
                    #    }
                    #}
                }
            },
            {
                "name": "fc1_act",
                "class": "keras.layers.advanced_activations.PReLU",
                "kwargs": {}
            },
            {
                "name": "fc1_dropout",
                "class": "keras.layers.core.Dropout",
                "kwargs": {
                    "p": 0.3
                }
            },
            {
                "name": "fc2",
                "class": "keras.layers.core.Dense",
                "kwargs": {
                    "output_dim": 100,
                    "activity_regularizer": {
                        "autoload": true,
                        "class": "keras.regularizers.ActivityRegularizer",
                        "kwargs": {
                            "l1": 1e-05
                        }
                    },
                    #"W_constraint": {
                    #    "autoload": true,
                    #    "class": "keras.constraints.maxnorm",
                    #    "kwargs": {
                    #        "m": 7,
                    #        "axis": 0
                    #    }
                    #}
                }
            },
            {
                "name": "fc2_act",
                "class": "keras.layers.advanced_activations.PReLU",
                "kwargs": {}
            },
            {
                "name": "fc2_dropout",
                "class": "keras.layers.core.Dropout",
                "kwargs": {
                    "p": 0.3
                }
            },
            {
                "name": "regression_task_act",
                "class": "keras.layers.core.Dense",
                "kwargs": {
                    "output_dim": 3,
                    "activation": "linear"
                }
            }
        ],
        "optimizer_config": {
            "class": "keras.optimizers.Adam",
            "kwargs": {
                "lr": 0.001
            }
        },
        "loss": "mean_squared_error"
          }
        },
        "model_trainer":{
            "class": "keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs": {
                "samples_per_epoch": 500000,
                "stopping_criterion_config": {
                    "class": "EarlyStopping" ,
                    "kwargs": {
                       "max_epochs": 300,
                       "epochs_to_wait": 10
                    }
                },
            }
        }
    }
    ]
    
