
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/atac_xferlearn_jul24/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
