
    {
        "class": "SequentialAccuracyStats",
        "kwargs": {"key_metric": "auPRC",
                   "all_metrics": ["auPRC",
                                   "auROC",
                                   "balanced_accuracy"]}
    }    
