
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/sharpr_qznormed_jul23/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
