
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../../model_files/classificationWithoutQcJun22/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
