[
{
        "other_data_loaders":{
            "train": {
                "class": "hdf5_data_loader.MultimodalBatchDataLoader",
                "kwargs": {
                    "batch_size": 500,
                    "path_to_hdf5": "../hdf5files/sharpr_qnormed_jul22/train_data.hdf5",
                    "num_to_load_for_eval": 100000,
                    "bundle_x_and_y_in_generator": False,
                    "strip_enclosing_dictionary": True
                }
            }
        },
    "model_creator":{
        "class": "flexible_keras.FlexibleKerasSequential",
        "kwargs": {
           "layers_config": [
            {
                "name": "conv1",
                "class": "keras.layers.convolutional.Convolution1D",
                "kwargs": {
                    "input_shape": [
                        145,
                        4
                    ],
                    "nb_filter": 100,
                    "filter_length": 5
                }
            }, 
            {
                "name": "conv1_act",
                "class": "keras.layers.core.Activation",
                "kwargs": {
                    "activation": "relu"
                }
            },
            {
                "name": "conv1_batchnorm",
                "class": "keras.layers.normalization.BatchNormalization",
                "kwargs": {
                    "axis": -1
                }
            },
            {
                "name": "conv1_dropout",
                "class": "keras.layers.core.Dropout",
                "kwargs": {
                    "p": 0.1
                }
            },
            # {
               # "name": "max_pool1",
               # "class": "keras.layers.convolutional.MaxPooling1D",
               # "kwargs": {
                   # "pool_length": 3,
                   # "stride": 3
               # }
            # },
            {
               "name": "conv2",
               "class": "keras.layers.convolutional.Convolution1D",
               "kwargs": {
                   "nb_filter": 100,
                   "filter_length": 9,
                   # "W_constraint": {
                       # "autoload": true,
                       # "class": "keras.constraints.maxnorm",
                       # "kwargs": {
                           # "m": 7,
                           # "axis": 0
                       # }
                   # }
               }
            }, 
            {
               "name": "conv2_act",
               "class": "keras.layers.core.Activation",
               "kwargs": {
                   "activation": "relu"
               }
            },
            {
               "name": "conv2_batchnorm",
               "class": "keras.layers.normalization.BatchNormalization",
               "kwargs": {
                   "axis": -1
               }
            },
            {
               "name": "conv2_dropout",
               "class": "keras.layers.core.Dropout",
               "kwargs": {
                   "p": 0.1
               }
            },
            # {
               # "name": "max_pool2",
               # "class": "keras.layers.convolutional.MaxPooling1D",
               # "kwargs": {
                   # "pool_length": 3,
                   # "stride": 3
               # }
            # },
            {
               "name": "conv3",
               "class": "keras.layers.convolutional.Convolution1D",
               "kwargs": {
                   "nb_filter": 100,
                   "filter_length": 5,
                   #"W_constraint": {
                   #    "autoload": true,
                   #    "class": "keras.constraints.maxnorm",
                   #    "kwargs": {
                   #        "m": 7,
                   #        "axis": 0
                   #    }
                   #}
               }
            },
            {
               "name": "conv3_batchnorm",
               "class": "keras.layers.normalization.BatchNormalization",
               "kwargs": {
                   "axis": -1
               }
            },
            {
               "name": "conv3_act",
               "class": "keras.layers.core.Activation",
               "kwargs": {
                   "activation": "relu"
               }
            },
            {
                "name": "conv3_dropout",
                "class": "keras.layers.core.Dropout",
                "kwargs": {
                    "p": 0.1
                }
            },
            # {
               # "name": "max_pool3",
               # "class": "keras.layers.convolutional.MaxPooling1D",
               # "kwargs": {
                   # "pool_length": 4,
                   # "stride": 4
               # }
            # },
            {
                "name": "flatten",
                "class": "keras.layers.core.Flatten",
                "kwargs": {}
            },
            # {
                # "name": "fc1",
                # "class": "keras.layers.core.Dense",
                # "kwargs": {
                    # "output_dim": 1000,
                    # "W_regularizer": {
                        # "autoload": true,
                        # "class": "keras.regularizers.WeightRegularizer",
                        # "kwargs": {
                            # "l2": 1e-05
                        # }
                    # },
                    # #"W_constraint": {
                    # #    "autoload": true,
                    # #    "class": "keras.constraints.maxnorm",
                    # #    "kwargs": {
                    # #        "m": 7,
                    # #        "axis": 0
                    # #    }
                    # #}
                # }
            # },
            # {
                # "name": "fc1_act",
                # "class": "keras.layers.advanced_activations.PReLU",
                # "kwargs": {}
            # },
            # {   
                # "name": "fc1_batchnorm",
                # "class": "keras.layers.normalization.BatchNormalization",
                # "kwargs": {
                    # "axis": -1
                # }
            # }, 
            # {
                # "name": "fc1_dropout",
                # "class": "keras.layers.core.Dropout",
                # "kwargs": {
                    # "p": 0.45
                # }
            # },
            # {
                # "name": "fc2",
                # "class": "keras.layers.core.Dense",
                # "kwargs": {
                    # "output_dim": 1000,
                    # "W_regularizer": {
                        # "autoload": true,
                        # "class": "keras.regularizers.WeightRegularizer",
                        # "kwargs": {
                            # "l1": 1e-05
                        # }
                    # },
                    # #"W_constraint": {
                    # #    "autoload": true,
                    # #    "class": "keras.constraints.maxnorm",
                    # #    "kwargs": {
                    # #        "m": 7,
                    # #        "axis": 0
                    # #    }
                    # #}
                # }
            # },
            # {
                # "name": "fc2_act",
                # "class": "keras.layers.advanced_activations.PReLU",
                # "kwargs": {}
            # },
            # {   
                # "name": "fc2_batchnorm",
                # "class": "keras.layers.normalization.BatchNormalization",
                # "kwargs": {
                    # "axis": -1
                # }
            # },
            # {
                # "name": "fc2_dropout",
                # "class": "keras.layers.core.Dropout",
                # "kwargs": {
                    # "p": 0.45
                # }
            # },
            {
                "name": "regression_task_act",
                "class": "keras.layers.core.Dense",
                "kwargs": {
                    "output_dim": 12,
                    "activation": "linear"
                }
            }
        ],
        "optimizer_config": {
            "class": "keras.optimizers.Adam",
            "kwargs": {
                "lr": 8e-5
            }
        },
        "loss": "mean_squared_error"
          }
        },
        "model_trainer":{
            "class": "keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs": {
                "samples_per_epoch": 200000,
                "stopping_criterion_config": {
                    "class": "EarlyStopping" ,
                    "kwargs": {
                        "max_epochs": 1000,
                       "epochs_to_wait": 20
                    }
                },
            }
        }
    }
    ]
    
