
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/classificationJun26/0.05subsample/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
