
    {
        "class": "hdf5_data_loader.MultimodalAtOnceDataLoader",
        "kwargs": {
           "path_to_hdf5": "../hdf5files/classificationJun26/0.05subsample/valid_data.hdf5",
           "strip_enclosing_dictionary": True,
           "max_to_load": 100000
        }
    }
    
