
    [
        {"class": "SaveBestValidModel",
         "kwargs": {"directory": "../model_files/counts_poisson_sep7/"}},
        {"class": "PrintPerfAfterEpoch",
         "kwargs": {"print_trend": true}}
    ]
    
